import { Copy, Flag, Plus } from "lucide-react";
import { requireSession } from "@/lib/auth/session";
import { getAdminContests } from "@/lib/services/admin";
import { createContestAction, duplicateContestAction, switchContestAction } from "@/lib/services/admin-actions";
import { Badge, Button, Card, Input } from "@/components/ui";

export default async function ContestsPage() {
  const session=await requireSession(["ADMIN","SUPER_ADMIN"]); const contests=await getAdminContests(session.id);
  return <main className="p-4 sm:p-7 lg:p-9"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.16em] text-sky-600">Multi-contest workspace</p><h1 className="mt-1 text-3xl font-black">การประกวดทั้งหมด</h1><p className="mt-2 text-slate-500">สลับ สร้าง หรือทำสำเนาการตั้งค่าโดยไม่คัดลอกผลงานและคะแนน</p></div><details><summary className="list-none"><span className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-2xl bg-slate-900 px-4 py-2 text-sm font-bold text-white"><Plus size={17}/> New contest</span></summary><Card className="absolute right-6 z-20 mt-2 w-[min(92vw,440px)] p-5"><form action={createContestAction} className="space-y-3"><h2 className="text-xl font-black">สร้างการประกวด</h2><Input name="name" placeholder="ชื่อการประกวด" required/><Input name="internalName" pattern="[a-z0-9][a-z0-9-]{1,79}" placeholder="internal-name" required/><textarea name="description" className="focus-ring min-h-24 w-full rounded-xl border border-blue-200 bg-white p-3" placeholder="รายละเอียดภายใน"/><Button className="w-full">Create draft</Button></form></Card></details></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2">{contests.map(contest=><Card key={contest.id} className={`p-5 ${contest.id===session.contestId?"ring-2 ring-sky-400":""}`}><div className="flex items-start justify-between gap-3"><span className="rounded-2xl bg-sky-100 p-3 text-sky-700"><Flag/></span><div className="flex gap-2"><Badge tone={contest.id===session.contestId?"blue":"slate"}>{contest.id===session.contestId?"CURRENT":"AVAILABLE"}</Badge><Badge tone={contest.status==="JUDGING"?"green":contest.status==="ARCHIVED"?"slate":"amber"}>{contest.status}</Badge></div></div><h2 className="mt-4 text-xl font-black">{contest.name}</h2><p className="mt-1 font-mono text-xs text-slate-400">{contest.internal_name}</p><p className="mt-3 line-clamp-2 min-h-10 text-sm text-slate-500">{contest.description||"ไม่มีรายละเอียด"}</p><div className="mt-4 flex gap-4 text-sm font-bold"><span>{contest.submissions} artworks</span><span>{contest.judges} judges</span></div><form action={switchContestAction} className="mt-4"><input type="hidden" name="contestId" value={contest.id}/><Button variant={contest.id===session.contestId?"secondary":"primary"} className="w-full" disabled={contest.id===session.contestId}>{contest.id===session.contestId?"Current contest":"Switch contest"}</Button></form>{contest.id===session.contestId&&<details className="mt-3"><summary className="cursor-pointer text-center text-sm font-bold text-sky-700"><Copy className="mr-1 inline" size={15}/> Duplicate settings</summary><form action={duplicateContestAction} className="mt-3 space-y-2 rounded-xl bg-sky-50 p-3"><input type="hidden" name="sourceContestId" value={contest.id}/><Input name="name" placeholder={`${contest.name} Copy`} required/><Input name="internalName" pattern="[a-z0-9][a-z0-9-]{1,79}" placeholder={`${contest.internal_name}-copy`} required/><Input name="confirmation" placeholder="พิมพ์ DUPLICATE" required/><Button variant="secondary" className="w-full">Duplicate contest</Button></form></details>}</Card>)}</div>
  </div></main>;
}
