import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowUp, ImageUp, Link2, Save, Trash2 } from "lucide-react";
import { requireSession } from "@/lib/auth/session";
import { query } from "@/lib/db";
import type { Submission } from "@/lib/db/types";
import { getSubmissionCategories } from "@/lib/services/admin";
import { archiveSubmissionAction, reorderSubmissionAction, replaceSubmissionImageAction, updateSubmissionAction, updateSubmissionStatusAction } from "@/lib/services/admin-actions";
import { ImageUploadField } from "@/components/admin/image-upload-field";
import { Badge, Button, Card, Input } from "@/components/ui";

export default async function SubmissionDetailPage({ params }: { params: Promise<{ submissionId: string }> }) {
  const session = await requireSession(["ADMIN", "SUPER_ADMIN"]);
  const { submissionId } = await params;
  const [submission, categories] = await Promise.all([
    query<Submission>("SELECT * FROM submissions WHERE id=$1 AND contest_id=$2", [submissionId, session.contestId]).then((rows)=>rows[0]),
    getSubmissionCategories(session.contestId!),
  ]);
  if (!submission) return <main className="p-8"><p>ไม่พบผลงาน</p></main>;
  return <main className="p-4 sm:p-7 lg:p-9"><div className="mx-auto max-w-5xl">
    <Link href="/admin/submissions" className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-bold text-sky-700"><ArrowLeft size={16}/> กลับไปรายการผลงาน</Link>
    <div className="mt-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-black uppercase tracking-[.16em] text-sky-600">Artwork #{submission.submission_number}</p><h1 className="mt-1 text-3xl font-black">แก้ไขข้อมูลผลงาน</h1></div><Badge tone={submission.status === "ACTIVE" ? "green" : "red"}>{submission.status}</Badge></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2">
      <Card className="p-5"><h2 className="text-xl font-black">Submission details</h2><form action={updateSubmissionAction} className="mt-4 grid gap-3"><input type="hidden" name="submissionId" value={submission.id}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Submission number<Input className="mt-1.5" name="submissionNumber" defaultValue={submission.submission_number} required/></label><label className="text-sm font-bold">Player ID<Input className="mt-1.5" name="playerId" defaultValue={submission.player_id} required/></label></div><label className="text-sm font-bold">Contestant name<Input className="mt-1.5" name="contestantName" defaultValue={submission.contestant_name} required/></label><label className="text-sm font-bold">Display name<Input className="mt-1.5" name="displayName" defaultValue={submission.display_name} required/></label><label className="text-sm font-bold">Artwork title<Input className="mt-1.5" name="artworkTitle" defaultValue={submission.artwork_title} required/></label><label className="text-sm font-bold">Artwork track<select name="categoryId" defaultValue={submission.category_id??""} className="focus-ring mt-1.5 min-h-11 w-full rounded-xl border border-blue-200 bg-white px-3" required><option value="">เลือกหมวดผลงาน</option>{categories.map(category=><option key={category.id} value={category.id}>{category.icon} {category.name}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Email<Input className="mt-1.5" name="email" type="email" defaultValue={submission.email??""}/></label><label className="text-sm font-bold">Social URL<Input className="mt-1.5" name="socialUrl" type="url" defaultValue={submission.social_url??""}/></label></div><label className="text-sm font-bold">Description<textarea className="focus-ring mt-1.5 min-h-24 w-full rounded-xl border border-blue-200 bg-white p-3" name="description" defaultValue={submission.description}/></label><label className="text-sm font-bold">Admin note<textarea className="focus-ring mt-1.5 min-h-24 w-full rounded-xl border border-blue-200 bg-white p-3" name="adminNote" defaultValue={submission.admin_note}/></label><Button><Save size={16}/> Save details</Button></form></Card>
      <Card className="h-fit p-5"><div className="flex items-center gap-2"><ImageUp className="text-sky-600"/><h2 className="text-xl font-black">Replace image</h2></div><img src={submission.image_url} alt={submission.artwork_title} className="mt-4 aspect-square w-full rounded-2xl bg-slate-100 object-contain"/><form action={replaceSubmissionImageAction} className="mt-4 space-y-3"><input type="hidden" name="submissionId" value={submission.id}/><ImageUploadField initialImageUrl={submission.source_image_url||submission.image_url} initialThumbnailUrl={submission.thumbnail_url??""}/><Input name="confirmation" placeholder="พิมพ์ REPLACE เพื่อยืนยัน" required/><Button variant="secondary" className="w-full">Replace image</Button></form>{submission.source_image_url&&<a href={submission.source_image_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-sky-700"><Link2 size={14}/> เปิดลิงก์ต้นฉบับ</a>}<p className="mt-3 text-xs text-slate-500">ไฟล์เดิมจะไม่ถูกลบอัตโนมัติ เพื่อคงหลักฐานและหลีกเลี่ยงการสูญหายโดยไม่ตั้งใจ</p></Card>
      <Card className="p-5 lg:col-span-2"><h2 className="text-xl font-black">Order & safe deletion</h2><p className="mt-1 text-sm text-slate-500">ขยับลำดับเฉพาะชิ้นนี้ หรือใช้เครื่องมือจัดเรียงทั้งคิวจากหน้ารายการผลงาน</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><form action={reorderSubmissionAction}><input type="hidden" name="submissionId" value={submission.id}/><input type="hidden" name="direction" value="up"/><Button variant="secondary" className="w-full"><ArrowUp size={16}/> Move up</Button></form><form action={reorderSubmissionAction}><input type="hidden" name="submissionId" value={submission.id}/><input type="hidden" name="direction" value="down"/><Button variant="secondary" className="w-full"><ArrowDown size={16}/> Move down</Button></form>{submission.status==="ARCHIVED"?<form action={updateSubmissionStatusAction}><input type="hidden" name="submissionId" value={submission.id}/><input type="hidden" name="status" value="ACTIVE"/><Button variant="secondary" className="w-full">Restore artwork</Button></form>:<form action={archiveSubmissionAction} className="flex gap-2"><input type="hidden" name="submissionId" value={submission.id}/><Input name="confirmation" placeholder="พิมพ์ DELETE" required/><Button variant="danger"><Trash2 size={16}/> Archive</Button></form>}</div></Card>
    </div>
  </div></main>;
}
